version: '3.9'

services:
  server:
    image: litio-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=$DATABASE_URL
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:16-alpine3.18
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
